services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  config-server-ms:
    container_name: config-server-ms
    image: robinroy1999/config-server-ms:latest
    ports:
      - "8085:8085"
    depends_on: 
      - servicereg
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    container_name: servicereg
    image: robinroy1999/servicereg:latest
    ports:
      - "8761:8761"
    depends_on: 
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - postgres
      - microservice-network

  companyms:
    container_name: company
    image: robinroy1999/companyms:latest
    ports:
      - "8083:8083"
    depends_on: 
      - servicereg
      - config-server-ms
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    container_name: job
    image: robinroy1999/jobms:latest
    ports:
      - "8082:8082"
    depends_on: 
      - servicereg
      - config-server-ms
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    container_name: review
    image: robinroy1999/reviewms:latest
    ports:
      - "8084:8084"
    depends_on: 
      - servicereg
      - config-server-ms
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway-ms:
    image: robinroy1999/gateway-ms:latest
    ports:
      - "8086:8086"
    depends_on: 
      - servicereg
    networks:
      - postgres
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
